@startuml "BaseService diagram"

class BaseService <T> {
    - collection:MongoCollection
    + BaseService(collection_name:str,db:MongoClient)
    + create(model:T)
    + read():T
    + update()
    + delete()
}

class UserService{
    - __secret_key:str
    + UserService(secret_key:str)
    + sign_up(email:str,password:str)
    - hash(key:str)->str
    - encrypt(key:str)->str
    - decrypt(key:str)->str
    - apikey_gen()->str
}

abstract class BaseHandler{
    + tag:str
    + route:str
    + app:FastAPI

    + BaseHandler(tag:str,route:str,app:FastAPI)
    + {abstract} register_path() -> None
}

class UserHandler{
    - user_service:UserService
    + UserHandler(tag:str, route:str,app:FastAPI)
    + register_path()->None
}

BaseService <|-- UserService: extend
UserHandler --|> BaseHandler: extend
UserService --o UserHandler:aggregate

@enduml