version: "3.2"

services:
  reverse_proxy:
    image: chunchunhuang/op_helios_httpserver:1.0.4
    ports:
      - "80:80"
      - "443:443"
    secrets:
      - source: revprox_cert
        target: revprox_cert
      - source: revprox_key
        target: revprox_key

    networks:
      - front-tier
    volumes:
     - ./nginx.conf:/etc/nginx/proxy.conf:ro
    deploy:
      restart_policy:
        condition: on-failure
      replicas: 1
    depends_on:
      - simulation_api


  simulation_api:
    image: chunchunhuang/op_helio_simulation_api:1.0.0
    ports:
      - 8000:8000
    secrets:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
      - api_secret
      - elasticsearch_password
      - googlemap_apikey
      - openweather_apikey
      - solcast_apikey
      - test_secret
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        failure_action: rollback

      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

    networks:
      - front-tier
      - back-tier

  mongodb:
    image: mongodb/mongodb-community-server
    secrets:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
    environment:
      - MONGO_INITDB_ROOT_USERNAME_FILE=/run/secrets/MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD_FILE=/run/secrets/MONGO_INITDB_ROOT_PASSWORD

    volumes:
      - mongo_config_db:/data/db

    deploy:
      replicas: 1

    networks:
      - back-tier

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.16.0
    secrets:
      - source: elasticsearch_password
        target: elasticsearch_password
        mode: 0444
    environment:
      - ELASTIC_PASSWORD_FILE=/run/secrets/elasticsearch_password
      - discovery.type=single-node
      - xpack.security.enabled=true
    volumes:
      - elasticsearch_simulation_db:/usr/share/elasticsearch/data

    deploy:
      replicas: 1

    networks:
      - back-tier

volumes:
  mongo_config_db:
    driver: local
    driver_opts:
      type: nfs
      o: addr=fs-038c1a3bfa3309477.efs.us-east-2.amazonaws.com,nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2
      device: "fs-038c1a3bfa3309477.efs.us-east-2.amazonaws.com:/capstone_mongo_persist"

  elasticsearch_simulation_db:
    driver: local
    driver_opts:
      type: nfs
      o: addr=fs-038c1a3bfa3309477.efs.us-east-2.amazonaws.com,nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2
      device: "fs-038c1a3bfa3309477.efs.us-east-2.amazonaws.com:/capstone_elasticsearch_persist"

networks:
  front-tier:
  back-tier:

secrets:
  MONGO_INITDB_ROOT_USERNAME:
    external: true
  MONGO_INITDB_ROOT_PASSWORD:
    external: true
  api_secret:
    external: true
  elasticsearch_password:
    external: true
  googlemap_apikey:
    external: true
  openweather_apikey:
    external: true
  solcast_apikey:
    external: true
  test_secret:
    external: true
  revprox_cert:
    external: true
  revprox_key:
    external: true
