version: "3.0"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - CONNECTION_STR=mongodb://user:pass@mongodb

    depends_on:
      mongodb:
        condition: service_healthy

  mongodb:
    image: mongodb/mongodb-community-server
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 30s
      start_period: 10s
      retries: 10
