version: "3.0"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - SECRET_KEY=Gkq3b7z8J9k8L1k9J8k3L1k9J8k3L1k9J8k3L1k9J8k=
      - CONNECTION_STR=mongodb://user:pass@mongodb
      - GOOGLEMAP_APIKEY=AIzaSyBF2slAi7qpMnjPkcsqkQ0R59rYN9sOnNA
      - OPENWEATHER_APIKEY=8bcf71b09bb730ee178c4d36c09206c1
      - SOLCAST_APIKEY=RmgJvrtEEwUTQp4eGIshBNuy2VK05gpv
    volumes:
      - ./app:/code/app
    depends_on:
      mongodb:
        condition: service_healthy

  mongodb:
    image: mongodb/mongodb-community-server
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass

    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 30s
      start_period: 10s
      retries: 10

    volumes:
      - testDB:/data/db

volumes:
  testDB:
