version: "3.0"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - SECRET_KEY=Gkq3b7z8J9k8L1k9J8k3L1k9J8k3L1k9J8k3L1k9J8k=
      - CONNECTION_STR=mongodb://user:pass@mongodb
      - GOOGLEMAP_APIKEY=AIzaSyBF2slAi7qpMnjPkcsqkQ0R59rYN9sOnNA
      - OPENWEATHER_APIKEY=8bcf71b09bb730ee178c4d36c09206c1
      - SOLCAST_APIKEY=RmgJvrtEEwUTQp4eGIshBNuy2VK05gpv
      # generate with `openssl x509 -fingerprint -sha256 -noout -in /path/to/http_ca.crt`
      - CERT_FINGERPRINT=0D:71:7E:DD:66:42:D8:BC:74:89:8D:8A:89:C7:CD:BD:1E:1C:68:E8:4D:3E:50:02:3F:FB:91:1E:44:D9:F3:68
      - ELASTIC_PASSWORD=changeme
      - ELASTIC_PATH=http://elasticsearch:9200
    volumes:
      - ./app:/code/app
    depends_on:
      mongodb:
        condition: service_healthy

  mongodb:
    image: mongodb/mongodb-community-server
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass

    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 30s
      start_period: 10s
      retries: 10

    volumes:
      - testDB:/data/db

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.3
    ports:
      - 9200:9200
    environment:
      - ELASTIC_PASSWORD=changeme
      - discovery.type=single-node
      - xpack.security.enabled=true

    healthcheck:
      test: ["CMD-SHELL", "curl -f https://localhost:9200 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  testDB:
